name: Tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Jest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      - run: npm install
        env:
          CI: TRUE
      - uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: 'npm run test:unit'
